cask_args appdir: '/Applications'

tap 'homebrew/bundle'

tap 'caskroom/fonts'

brew 'ansible'
brew 'coreutils'
brew 'imagemagick@6'
brew 'go'
brew 'git'
brew 'grc'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'mongodb'
brew 'mysql'
brew 'openssl'
brew 'qt'
brew 'readline'
brew 'redis'
brew 'terraform'
brew 'tree'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'font-fira-code'
cask 'google-chrome'
cask 'iterm2'
cask 'mysqlworkbench'
cask 'postman'
cask 'sizeup'
cask 'sourcetree'
cask 'slack'
cask 'tunnelbear'
cask 'visual-studio-code'
cask 'zeplin'
